### ISSUE TITLE
Is there a easy way to pass a list of payload files?

### ISSUE THREAD

**Issue by riramar** [deibit/cansina#22]
Is there a easy way to pass a list of payload files?
Something like these:

`$ ./cansina.py -u https://xxxx.xxxx.xxx -p ../Payloads/SecLists/Discovery/Web_Content/*`

**Comment by deibit** [comment]
We have been discussing the method you proposed, pass a folder instead of a single file. In the meantime, as a workaround you can use the stdin, concatenating various files, something like:

`ls *.txt | xargs -I {} cat {} | ./cansina.py -u ... -p -`

Didn't try myself, but should work. Regarding your proposal, yes, it will be implemented soon or later.

**Comment by deibit** [comment]
Done in a5c708e20f69e37ce417f6feb1d4dfc899940267. Check how to in https://github.com/deibit/cansina/wiki/Payload-files-or-compilations

**Comment by riramar** [comment]
It worked here. 👍 
```
# ./cansina.py -u https://xxx.xxx.xxx -p ../Payloads/SecLists/Discovery/Web_Content/
Resolving xxx.xxx.xxx
HTTP GET requests
Banned response codes: 404
Using payload: ../Payloads/SecLists/Discovery/Web_Content/
Generating payloads...
[*] Directory payload inclusion. All *.txt will be treated as a payload.
Spawning 4 threads 
```
