### ISSUE TITLE
Disable redirect

### ISSUE THREAD

**Issue by riramar** [deibit/cansina#23]
This is feature request to include an option for disable redirection or maybe check if the redirection point to another domain.
Some times redirect can send you to a default page or another domain that probably always return 200.

**Comment by deibit** [comment]
Yeah, redirection hasn't been handled since a while in a proper way, so I commented the code and went on. I just added a '--no-follow' option in a0cbe6bc3aec289d2001eea0c0c0d886fd65a91b, which set 'allow_redirects' (requests) to False. Without '--no-follow', hence the default case, redirections will be handled unless is the "dash redirection" to the same page. 

Anyway, I'm still not happy with redirections. There are old dead code designed as a auto-detect and ban dumb redirections (to root, external domain, etc...) which I would like to retake in a more granular treatment. Closing this issue as '--no-follow' has been implemented, but it's on the road a better and smarter handling.

**Comment by riramar** [comment]
Thanks a lot for the explanation. I have more experience with urllib than request which is pretty easy to handle redirects. I'll try to check requests lib and maybe send a PR.
Another cool thing that you could implement is something similar to sqlmap. Imagine that the user didn't provide the --no-follow option but cansina detect three (or more) consecutive redirects to the same page so cansine could pause the scan and ask the user if he/she wants to do not follow redirects anymore. BTW the resume feature is amazing!

**Comment by deibit** [comment]
I'll be glad to have a second view on redirects, until now I'm not happy the way it is. 

Regarding the sqlmap alike feature, yes, I'm designing a message queue to handle errors, detections, pausing and other kind of features. 

I'm afraid resume feature will need a review due to the modified payload and recursive options. It's on agenda.  Thanks
